services:
  my_vocabs:
    image: my_vocabs:latest
    build:
      context: .
      dockerfile: ./cmd/my_vocabs/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    restart: unless-stopped
