// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Vocab struct {
	VocabID      string             `json:"vocab_id"`
	Word         string             `json:"word"`
	ImageUrls    []string           `json:"image_urls"`
	NextReview   pgtype.Timestamptz `json:"next_review"`
	ReviewedTime pgtype.Int4        `json:"reviewed_time"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
