// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateVocab(ctx context.Context, arg CreateVocabParams) (Vocab, error)
	DeleteVocabByName(ctx context.Context, word string) (Vocab, error)
	GetVocabByName(ctx context.Context, word string) (Vocab, error)
	ListVocabs(ctx context.Context) ([]Vocab, error)
	ListVocabsByFilter(ctx context.Context, dollar_1 interface{}) ([]Vocab, error)
	ReviewVocabs(ctx context.Context) ([]Vocab, error)
	UpdateNextReviewByName(ctx context.Context, arg UpdateNextReviewByNameParams) (Vocab, error)
}

var _ Querier = (*Queries)(nil)
