// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateVocab(ctx context.Context, arg CreateVocabParams) (Vocab, error)
	ListVocabs(ctx context.Context) ([]Vocab, error)
}

var _ Querier = (*Queries)(nil)
