// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: vocab.sql

package db

import (
	"context"
)

const createVocab = `-- name: CreateVocab :one
INSERT INTO vocab (
    vocab_id,
    word,
    image_urls
) VALUES (
    $1, $2, $3
) RETURNING vocab_id, word, image_urls, created_at, updated_at, deleted_at
`

type CreateVocabParams struct {
	VocabID   string   `json:"vocab_id"`
	Word      string   `json:"word"`
	ImageUrls []string `json:"image_urls"`
}

func (q *Queries) CreateVocab(ctx context.Context, arg CreateVocabParams) (Vocab, error) {
	row := q.db.QueryRow(ctx, createVocab, arg.VocabID, arg.Word, arg.ImageUrls)
	var i Vocab
	err := row.Scan(
		&i.VocabID,
		&i.Word,
		&i.ImageUrls,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listVocabs = `-- name: ListVocabs :many
SELECT vocab_id, word, image_urls, created_at, updated_at, deleted_at FROM vocab ORDER BY created_at
`

func (q *Queries) ListVocabs(ctx context.Context) ([]Vocab, error) {
	rows, err := q.db.Query(ctx, listVocabs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vocab{}
	for rows.Next() {
		var i Vocab
		if err := rows.Scan(
			&i.VocabID,
			&i.Word,
			&i.ImageUrls,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
